### ISSUE TITLE
New release for for conda-forge

### ISSUE THREAD

**Issue by jhkennedy** [ClimateGlobalChange/tempestremap#49]
With the inclusion of the netCDF-CXX legacy framework in 30c3e4c02fd671bf767ca4f58267550921d4130b, I was able to build a conda package on the e3sm channel (for linux). Since then I've done a bit of playing around, and I think we could put Tempest Remap onto conda-forge with a new Tempest Remap release (and possibly @xylar 's help if he's willing). 

For the e3sm channel, I've been able to point to a specific version in the repo like: 

```yaml
source:
  git_url: https://github.com/ClimateGlobalChange/tempestremap.git
  git_rev: 30c3e4c02fd671bf767ca4f58267550921d4130b
```

However, this isn't allowed on conda-forge as they require you to [build from tarballs, not repos](http://conda-forge.org/docs/maintainer/adding_pkgs.html#tarballs-no-repos).
